<a href="https://colab.research.google.com/github/Rancor06/Salman-Inten-Projects/blob/main/Phase%202/Day%2012/Tasks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
from google.colab import files
import pandas as pd
import numpy as np
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.metrics import precision_score, recall_score, f1_score
from sklearn.preprocessing import StandardScaler
import io
import warnings
warnings.filterwarnings('ignore')

# Upload file from local drive
uploaded = files.upload()

Saving student_performance.csv to student_performance (1).csv


In [12]:
# Load The Dataset
df = pd.read_csv(io.BytesIO(uploaded['student_performance (1).csv']))

# Select Features and Target Variable
X = df.drop(columns=['student_id', 'grade','total_score'])
Y = df['grade']

# Train - Test Split
X_train, X_test, y_train, y_test = train_test_split(
    X, Y, test_size=0.2, random_state=42
)
print("Training Sample Shape: ",X_train.shape)
print("Testing Sample Shape: ",X_test.shape)

# Scale features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

Training Sample Shape:  (800000, 3)
Testing Sample Shape:  (200000, 3)


In [13]:
# TASK 1: LOGISTIC REGRESSION MODEL
# Train
log_model = LogisticRegression(max_iter=1000)
log_model.fit(X_train_scaled, y_train)

print("Logistic Regression Model has been successfully trained")

# Predict
y_pred_log = log_model.predict(X_test_scaled)

# Evaluate
print("Accuracy:", accuracy_score(y_test, y_pred_log))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_log))
print("\nClassification Report:\n", classification_report(y_test, y_pred_log))

Logistic Regression Model has been successfully trained
Accuracy: 0.69699

Confusion Matrix:
 [[97144 12160   582     2     0]
 [18507 26288  6555   206     0]
 [ 1720 11704 12835  2121     0]
 [   23   969  4804  3131     0]
 [    0    17   402   830     0]]

Classification Report:
               precision    recall  f1-score   support

           A       0.83      0.88      0.85    109888
           B       0.51      0.51      0.51     51556
           C       0.51      0.45      0.48     28380
           D       0.50      0.35      0.41      8927
           F       0.00      0.00      0.00      1249

    accuracy                           0.70    200000
   macro avg       0.47      0.44      0.45    200000
weighted avg       0.68      0.70      0.69    200000



In [14]:
# TASK 2: KNN CLASSIFIER MODEL
# K = 3, 5, 7
k_values = [3, 5, 7]
knn_results = {}

for k in k_values:
    knn = KNeighborsClassifier(n_neighbors=k, n_jobs=-1)
    knn.fit(X_train_scaled, y_train)
    y_pred_knn = knn.predict(X_test_scaled)
    acc = accuracy_score(y_test, y_pred_knn)
    knn_results[k] = acc
    print(f"K={k} -> Accuracy: {acc:.4f}")

print("KNN Classifier Model has been successfully trained")

# Best K
best_k = max(knn_results, key=knn_results.get)
print(f"\nBest K: {best_k} with Accuracy: {knn_results[best_k]:.4f}")

# Retrain KNN with the best K found to finalize
best_knn = KNeighborsClassifier(n_neighbors=best_k, n_jobs=-1)
best_knn.fit(X_train_scaled, y_train)
y_pred_knn = best_knn.predict(X_test_scaled)

K=3 -> Accuracy: 0.6356
K=5 -> Accuracy: 0.6542
K=7 -> Accuracy: 0.6637
KNN Classifier Model has been successfully trained

Best K: 7 with Accuracy: 0.6637


In [15]:
# TASK 3 DECISION TREE CLASSIFIER MODEL
# Train
dt_model = DecisionTreeClassifier(random_state=42)
dt_model.fit(X_train, y_train)

print("Decision Tree Classifier Model has been successfully trained")

# Predict
y_pred_dt = dt_model.predict(X_test)

# Evaluate
print("Accuracy:", accuracy_score(y_test, y_pred_dt))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred_dt))
print("\nClassification Report:\n", classification_report(y_test, y_pred_dt))

Decision Tree Classifier Model has been successfully trained
Accuracy: 0.609205

Confusion Matrix:
 [[88077 18131  3472   204     4]
 [19592 20691  9615  1576    82]
 [ 3832 10064 10186  3841   457]
 [  258  1616  3778  2763   512]
 [    2   100   490   533   124]]

Classification Report:
               precision    recall  f1-score   support

           A       0.79      0.80      0.79    109888
           B       0.41      0.40      0.41     51556
           C       0.37      0.36      0.36     28380
           D       0.31      0.31      0.31      8927
           F       0.11      0.10      0.10      1249

    accuracy                           0.61    200000
   macro avg       0.40      0.39      0.40    200000
weighted avg       0.61      0.61      0.61    200000



In [16]:
# TASK 4: BUILD COMPARISON TABLE
comparison = pd.DataFrame({
    'Model': ['Logistic Regression', 'KNN', 'Decision Tree'],
    'Accuracy': [
        accuracy_score(y_test, y_pred_log),
        accuracy_score(y_test, y_pred_knn),
        accuracy_score(y_test, y_pred_dt)
    ],
    'Precision': [
        precision_score(y_test, y_pred_log, average='weighted'),
        precision_score(y_test, y_pred_knn, average='weighted'),
        precision_score(y_test, y_pred_dt, average='weighted')
    ],
    'Recall': [
        recall_score(y_test, y_pred_log, average='weighted'),
        recall_score(y_test, y_pred_knn, average='weighted'),
        recall_score(y_test, y_pred_dt, average='weighted')
    ],
    'F1-Score': [
        f1_score(y_test, y_pred_log, average='weighted'),
        f1_score(y_test, y_pred_knn, average='weighted'),
        f1_score(y_test, y_pred_dt, average='weighted')
    ]
})
print("Comparison Table:")
print(comparison)

Comparison Table:
                 Model  Accuracy  Precision    Recall  F1-Score
0  Logistic Regression  0.696990   0.681733  0.696990  0.688034
1                  KNN  0.663695   0.646130  0.663695  0.653060
2        Decision Tree  0.609205   0.605379  0.609205  0.607239


In [19]:
# TASK 5: PREDICT NEW DATA
# Create 5 new sample students
new_data = pd.DataFrame({
    'weekly_self_study_hours': [5, 15, 22, 8, 28],
    'attendance_percentage': [60, 85, 95, 70, 99],
    'class_participation': [3, 6, 9, 4, 10]
})
print("5 new sample records:")
print(new_data)

# Predict with Logistic Regression (unscaled)
pred_log_new = log_model.predict(new_data)

# Predict with Decision Tree (unscaled)
pred_dt_new = dt_model.predict(new_data)

# Predict with KNN (needs scaling first!)
new_data_scaled = scaler.transform(new_data)
pred_knn_new = best_knn.predict(new_data_scaled)

# Compare all predictions side by side
predictions_comparison = pd.DataFrame({
    'Student': [1, 2, 3, 4, 5],
    'Study Hours': new_data['weekly_self_study_hours'],
    'Attendance %': new_data['attendance_percentage'],
    'Participation': new_data['class_participation'],
    'LogReg Prediction': pred_log_new,
    'KNN Prediction': pred_knn_new,
    'Decision Tree Prediction': pred_dt_new
})
print("\nComparison of Predictions:")
print(predictions_comparison)

5 new sample records:
   weekly_self_study_hours  attendance_percentage  class_participation
0                        5                     60                    3
1                       15                     85                    6
2                       22                     95                    9
3                        8                     70                    4
4                       28                     99                   10

Comparison of Predictions:
   Student  Study Hours  Attendance %  Participation LogReg Prediction  \
0        1            5            60              3                 A   
1        2           15            85              6                 A   
2        3           22            95              9                 A   
3        4            8            70              4                 A   
4        5           28            99             10                 A   

  KNN Prediction Decision Tree Prediction  
0              B                   

In [18]:
# TASK 6: BEST MODEL
best_row = comparison.loc[comparison['Accuracy'].idxmax()]

print("Best Model:", best_row['Model'])
print("Best Accuracy:", round(best_row['Accuracy'], 4))
print("\nWhy this model was selected:")
print(f"{best_row['Model']} achieved the highest accuracy ({best_row['Accuracy']:.4f}) "
      f"among the three models tested. It also showed strong precision "
      f"({best_row['Precision']:.4f}) and recall ({best_row['Recall']:.4f}), "
      f"indicating balanced performance across grade classes despite the dataset's imbalance.")

Best Model: Logistic Regression
Best Accuracy: 0.697

Why this model was selected:
Logistic Regression achieved the highest accuracy (0.6970) among the three models tested. It also showed strong precision (0.6817) and recall (0.6970), indicating balanced performance across grade classes despite the dataset's imbalance.
